# Generated by Django 5.1.2 on 2024-12-12 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
                ('data_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
