# Generated by Django 5.1.2 on 2025-01-28 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registered_doors',
            field=models.ManyToManyField(blank=True, related_name='users', to='rooms.door'),
        ),
    ]
