# Generated by Django 5.1.2 on 2025-02-08 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_registered_doors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_by',
            field=models.CharField(blank=True, default='Admin', max_length=200, null=True),
        ),
    ]
