# Generated by Django 5.1.2 on 2025-03-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fingerprint_template',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
