# Generated by Django 5.1.2 on 2025-03-25 04:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='tenants',
            field=models.ManyToManyField(blank=True, related_name='registered_doors_in_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
