# Generated by Django 5.1.2 on 2025-03-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_door_is_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='created_by',
            field=models.CharField(default='Admin', max_length=200),
        ),
    ]
